"""
make_histogram.py - Generate temperature statistics histograms for Task 12.
Usage: python make_histogram.py
Requires: results_all.csv (generated by the final processing job)
"""
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('results_all.csv')

fig, axes = plt.subplots(2, 2, figsize=(12, 9))
fig.suptitle('Temperature statistics — 4,571 buildings', fontsize=13)

axes[0,0].hist(df.mean_temp, bins=40, color='royalblue', edgecolor='white')
axes[0,0].axvline(18, color='red', linestyle='--', label='18°C')
axes[0,0].set_xlabel('Mean temperature (°C)')
axes[0,0].set_ylabel('Number of buildings')
axes[0,0].set_title('Distribution of mean temperatures')
axes[0,0].legend()

axes[0,1].hist(df.std_temp, bins=40, color='orange', edgecolor='white')
axes[0,1].set_xlabel('Std deviation (°C)')
axes[0,1].set_ylabel('Number of buildings')
axes[0,1].set_title('Distribution of std deviations')

axes[1,0].hist(df.pct_above_18, bins=40, color='green', edgecolor='white')
axes[1,0].axvline(50, color='red', linestyle='--', label='50% threshold')
axes[1,0].set_xlabel('% area above 18°C')
axes[1,0].set_ylabel('Number of buildings')
axes[1,0].set_title('% of room area above 18°C')
axes[1,0].legend()

axes[1,1].hist(df.pct_below_15, bins=40, color='tomato', edgecolor='white')
axes[1,1].axvline(50, color='black', linestyle='--', label='50% threshold')
axes[1,1].set_xlabel('% area below 15°C')
axes[1,1].set_ylabel('Number of buildings')
axes[1,1].set_title('% of room area below 15°C')
axes[1,1].legend()

plt.tight_layout()
plt.savefig('part4_task12_analysis.png', dpi=150, bbox_inches='tight')
print('Saved: part4_task12_analysis.png')
